app:
  url:
    base: ${URL_APP:https://data-services-api.devchampions.cloud}
    path-wiki: { URL_PATH_WIKI:/wiki }
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:"Data Services API"}
    version: ${SPRING_APPLICATION_VERSION:1.0.0}