spring:
  datasource:
    url: jdbc:h2:mem:dataservices
    driver-class-name: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

app:
  url:
    base: ${URL_APP:https://www.dataservicesapi.devchampions.com.br}
    path-wiki: { URL_PATH_WIKI:/wiki }