app:
  url:
    base: ${URL_APP:https://www.dataservicesapi.devchampions.com.br}
    path-wiki: { URL_PATH_WIKI:/wiki }
spring:
  data:
    web:
      pageable:
        max-page-size: 50
        default-page-size: 10
    rest:
      max-page-size: 50
      default-page-size: 10
