--liquibase formatted sql
--changeset dherkyan.silva:1

INSERT INTO tb02_pais(nome, alpha2, alpha3, numerico3, dominio)
VALUES ('Afeganistão', 'AF', 'AFG', '004', '.af'),
       ('África do Sul', 'ZA', 'ZAF', '710', '.za'),
       ('Albânia', 'AL', 'ALB', '008', '.al'),
       ('Alemanha', 'DE', 'DEU', '276', '.de'),
       ('Andorra', 'AD', 'AND', '020', '.ad'),
       ('Angola', 'AO', 'AGO', '024', '.ao'),
       ('Anguila', 'AI', 'AIA', '660', '.ai'),
       ('Antártica', 'AQ', 'ATA', '010', '.aq'),
       ('Antígua e Barbuda', 'AG', 'ATG', '028', '.ag'),
       ('Arábia Saudita', 'SA', 'SAU', '682', '.sa'),
       ('Argélia', 'DZ', 'DZA', '012', '.dz'),
       ('Argentina', 'AR', 'ARG', '032', '.ar'),
       ('Armênia', 'AM', 'ARM', '051', '.am'),
       ('Aruba', 'AW', 'ABW', '533', '.aw'),
       ('Austrália', 'AU', 'AUS', '036', '.au'),
       ('Áustria', 'AT', 'AUT', '040', '.at'),
       ('Azerbaijão', 'AZ', 'AZE', '031', '.az'),
       ('Bahamas', 'BS', 'BHS', '044', '.bs'),
       ('Bahrein', 'BH', 'BHR', '048', '.bh'),
       ('Bangladesh', 'BD', 'BGD', '050', '.bd'),
       ('Barbados', 'BB', 'BRB', '052', '.bb'),
       ('Belarus', 'BY', 'BLR', '112', '.by'),
       ('Bélgica', 'BE', 'BEL', '056', '.be'),
       ('Belize', 'BZ', 'BLZ', '084', '.bz'),
       ('Benin', 'BJ', 'BEN', '204', '.bj'),
       ('Bermudas', 'BM', 'BMU', '060', '.bm'),
       ('Bolívia', 'BO', 'BOL', '068', '.bo'),
       ('Bósnia e Herzegovina', 'BA', 'BIH', '070', '.ba'),
       ('Botsuana', 'BW', 'BWA', '072', '.bw'),
       ('Brasil', 'BR', 'BRA', '076', '.br'),
       ('Brunei', 'BN', 'BRN', '096', '.bn'),
       ('Bulgária', 'BG', 'BGR', '100', '.bg'),
       ('Burkina Faso', 'BF', 'BFA', '854', '.bf'),
       ('Burundi', 'BI', 'BDI', '108', '.bi'),
       ('Butão', 'BT', 'BTN', '064', '.bt'),
       ('Cabo Verde', 'CV', 'CPV', '132', '.cv'),
       ('Camarões', 'CM', 'CMR', '120', '.cm'),
       ('Camboja', 'KH', 'KHM', '116', '.kh'),
       ('Canadá', 'CA', 'CAN', '124', '.ca'),
       ('Cazaquistão', 'KZ', 'KAZ', '398', '.kz'),
       ('Chade', 'TD', 'TCD', '148', '.td'),
       ('Chile', 'CL', 'CHL', '152', '.cl'),
       ('China', 'CN', 'CHN', '156', '.cn'),
       ('Chipre', 'CY', 'CYP', '196', '.cy'),
       ('Cidade do Vaticano', 'VA', 'VAT', '336', '.va'),
       ('Cingapura', 'SG', 'SGP', '702', '.sg'),
       ('Colômbia', 'CO', 'COL', '170', '.co'),
       ('Comores', 'KM', 'COM', '174', '.km'),
       ('Coréia do Norte', 'KP', 'PRK', '408', '.kp'),
       ('Coréia do Sul', 'KR', 'KOR', '410', '.kr'),
       ('Costa do Marfim', 'CI', 'CIV', '384', '.ci'),
       ('Costa Rica', 'CR', 'CRI', '188', '.cr'),
       ('Croácia', 'HR', 'HRV', '191', '.hr'),
       ('Cuba', 'CU', 'CUB', '192', '.cu'),
       ('Curaçao', 'CW', 'CUW', '531', '.cw'),
       ('Dinamarca', 'DK', 'DNK', '208', '.dk'),
       ('Djibouti', 'DJ', 'DJI', '262', '.dj'),
       ('Dominica', 'DM', 'DMA', '212', '.dm'),
       ('Egito', 'EG', 'EGY', '818', '.eg'),
       ('El Salvador', 'SV', 'SLV', '222', '.sv'),
       ('Emirados Árabes Unidos', 'AE', 'ARE', '784', '.ae'),
       ('Equador', 'EC', 'ECU', '218', '.ec'),
       ('Eritreia', 'ER', 'ERI', '232', '.er'),
       ('Eslováquia', 'SK', 'SVK', '703', '.sk'),
       ('Eslovênia', 'SI', 'SVN', '705', '.si'),
       ('Espanha', 'ES', 'ESP', '724', '.es'),
       ('Estados Federados da Micronésia', 'FM', 'FSM', '583', '.fm'),
       ('Estados Unidos da América', 'US', 'USA', '840', '.us'),
       ('Estônia', 'EE', 'EST', '233', '.ee'),
       ('Eswatini', 'SZ', 'SWZ', '748', '.sz'),
       ('Etiópia', 'ET', 'ETH', '231', '.et'),
       ('Fiji', 'FJ', 'FJI', '242', '.fj'),
       ('Filipinas', 'PH', 'PHL', '608', '.ph'),
       ('Finlândia', 'FI', 'FIN', '246', '.fi'),
       ('França', 'FR', 'FRA', '250', '.fr'),
       ('Gabão', 'GA', 'GAB', '266', '.ga'),
       ('Gâmbia', 'GM', 'GMB', '270', '.gm'),
       ('Gana', 'GH', 'GHA', '288', '.gh'),
       ('Geórgia', 'GE', 'GEO', '268', '.ge'),
       ('Geórgia do Sul e as Ilhas Sandwich do Sul', 'GS', 'SGS', '239', '.gs'),
       ('Gibraltar', 'GI', 'GIB', '292', '.gi'),
       ('Grécia', 'GR', 'GRC', '300', '.gr'),
       ('Grenada', 'GD', 'GRD', '308', '.gd'),
       ('Groenlândia', 'GL', 'GRL', '304', '.gl'),
       ('Guadalupe', 'GP', 'GLP', '312', '.gp'),
       ('Guam', 'GU', 'GUM', '316', '.gu'),
       ('Guatemala', 'GT', 'GTM', '320', '.gt'),
       ('Guernsey', 'GG', 'GGY', '831', '.gg'),
       ('Guiana', 'GY', 'GUY', '328', '.gy'),
       ('Guiana Francesa', 'GF', 'GUF', '254', '.gf'),
       ('Guiné', 'GN', 'GIN', '324', '.gn'),
       ('Guiné Equatorial', 'GQ', 'GNQ', '226', '.gq'),
       ('Guiné-Bissau', 'GW', 'GNB', '624', '.gw'),
       ('Haiti', 'HT', 'HTI', '332', '.ht'),
       ('Honduras', 'HN', 'HND', '340', '.hn'),
       ('Hong Kong', 'HK', 'HKG', '344', '.hk'),
       ('Hungria', 'HU', 'HUN', '348', '.hu'),
       ('Iêmen', 'YE', 'YEM', '887', '.ye'),
       ('Ilha Bouvet', 'BV', 'BVT', '074', '.bv'),
       ('Ilha da Reunião', 'RE', 'REU', '638', '.re'),
       ('Ilha de Man', 'IM', 'IMN', '833', '.im'),
       ('Ilha de Natal', 'CX', 'CXR', '162', '.cx'),
       ('Ilha Norfolk', 'NF', 'NFK', '574', '.nf'),
       ('Ilhas Åland', 'AX', 'ALA', '248', '.ax'),
       ('Ilhas Cayman', 'KY', 'CYM', '136', '.ky'),
       ('Ilhas Cocos', 'CC', 'CCK', '166', '.cc'),
       ('Ilhas Cook', 'CK', 'COK', '184', '.ck'),
       ('Ilhas Faroe', 'FO', 'FRO', '234', '.fo'),
       ('Ilhas Malvinas', 'FK', 'FLK', '238', '.fk'),
       ('Ilhas Marianas do Norte', 'MP', 'MNP', '580', '.mp'),
       ('Ilhas Marshall', 'MH', 'MHL', '584', '.mh'),
       ('Ilhas Menores Distantes dos Estados Unidos', 'UM', 'UMI', '581', '.us'),
       ('Ilhas Pitcairn', 'PN', 'PCN', '612', '.pn'),
       ('Ilhas Salomão', 'SB', 'SLB', '090', '.sb'),
       ('Ilhas Turcas e Caicos', 'TC', 'TCA', '796', '.tc'),
       ('Ilhas Virgens (Reino Unido)', 'VG', 'VGB', '092', '.vg'),
       ('Ilhas Virgens dos Estados Unidos', 'VI', 'VIR', '850', '.vi'),
       ('Índia', 'IN', 'IND', '356', '.in'),
       ('Indonésia', 'ID', 'IDN', '360', '.id'),
       ('Irã', 'IR', 'IRN', '364', '.ir'),
       ('Iraque', 'IQ', 'IRQ', '368', '.iq'),
       ('Irlanda', 'IE', 'IRL', '372', '.ie'),
       ('Islândia', 'IS', 'ISL', '352', '.is'),
       ('Israel', 'IL', 'ISR', '376', '.il'),
       ('Itália', 'IT', 'ITA', '380', '.it'),
       ('Jamaica', 'JM', 'JAM', '388', '.jm'),
       ('Japão', 'JP', 'JPN', '392', '.jp'),
       ('Jersey', 'JE', 'JEY', '832', '.je'),
       ('Jordânia', 'JO', 'JOR', '400', '.jo'),
       ('Kiribati', 'KI', 'KIR', '296', '.ki'),
       ('Kosovo', 'XK', 'XXK', '412', '.ko'),
       ('Kuwait', 'KW', 'KWT', '414', '.kw'),
       ('Laos', 'LA', 'LAO', '418', '.la'),
       ('Lesotho', 'LS', 'LSO', '426', '.ls'),
       ('Letônia', 'LV', 'LVA', '428', '.lv'),
       ('Líbano', 'LB', 'LBN', '422', '.lb'),
       ('Libéria', 'LR', 'LBR', '430', '.lr'),
       ('Líbia', 'LY', 'LBY', '434', '.ly'),
       ('Liechtenstein', 'LI', 'LIE', '438', '.li'),
       ('Lituânia', 'LT', 'LTU', '440', '.lt'),
       ('Luxemburgo', 'LU', 'LUX', '442', '.lu'),
       ('Macau', 'MO', 'MAC', '446', '.mo'),
       ('Madagascar', 'MG', 'MDG', '450', '.mg'),
       ('Malásia', 'MY', 'MYS', '458', '.my'),
       ('Malauí', 'MW', 'MWI', '454', '.mw'),
       ('Maldivas', 'MV', 'MDV', '462', '.mv'),
       ('Mali', 'ML', 'MLI', '466', '.ml'),
       ('Malta', 'MT', 'MLT', '470', '.mt'),
       ('Marrocos', 'MA', 'MAR', '504', '.ma'),
       ('Martinica', 'MQ', 'MTQ', '474', '.mq'),
       ('Maurício', 'MU', 'MUS', '480', '.mu'),
       ('Mauritânia', 'MR', 'MRT', '478', '.mr'),
       ('Mayotte', 'YT', 'MYT', '175', '.yt'),
       ('México', 'MX', 'MEX', '484', '.mx'),
       ('Mianmar', 'MM', 'MMR', '104', '.mm'),
       ('Moçambique', 'MZ', 'MOZ', '508', '.mz'),
       ('Moldávia', 'MD', 'MDA', '498', '.md'),
       ('Mongólia', 'MN', 'MNG', '496', '.mn'),
       ('Montenegro', 'ME', 'MNE', '499', '.me'),
       ('Montserrat', 'MS', 'MSR', '500', '.ms'),
       ('Namíbia', 'NA', 'NAM', '516', '.na'),
       ('Nauru', 'NR', 'NRU', '520', '.nr'),
       ('Nepal', 'NP', 'NPL', '524', '.np'),
       ('Nicarágua', 'NI', 'NIC', '558', '.ni'),
       ('Níger', 'NE', 'NER', '562', '.ne'),
       ('Nigéria', 'NG', 'NGA', '566', '.ng'),
       ('Niue', 'NU', 'NIU', '570', '.nu'),
       ('Norte da Macedônia', 'MK', 'MKD', '807', '.mk'),
       ('Noruega', 'NO', 'NOR', '578', '.no'),
       ('Nova Caledônia', 'NC', 'NCL', '540', '.nc'),
       ('Nova Zelândia', 'NZ', 'NZL', '554', '.nz'),
       ('Omã', 'OM', 'OMN', '512', '.om'),
       ('Ouvido e Ilhas McDonald', 'HM', 'HMD', '334', '.hm'),
       ('Países Baixos', 'NL', 'NLD', '528', '.nl'),
       ('Países Baixos Caribenhos', 'BQ', 'BES', '535', '.bq'),
       ('Palau', 'PW', 'PLW', '585', '.pw'),
       ('Palestina', 'PS', 'PSE', '275', '.ps'),
       ('Panamá', 'PA', 'PAN', '591', '.pa'),
       ('Papua Nova Guiné', 'PG', 'PNG', '598', '.pg'),
       ('Paquistão', 'PK', 'PAK', '586', '.pk'),
       ('Paraguai', 'PY', 'PRY', '600', '.py'),
       ('Peru', 'PE', 'PER', '604', '.pe'),
       ('Polinésia Francesa', 'PF', 'PYF', '258', '.pf'),
       ('Polônia', 'PL', 'POL', '616', '.pl'),
       ('Porto Rico', 'PR', 'PRI', '630', '.pr'),
       ('Portugal', 'PT', 'PRT', '620', '.pt'),
       ('Principado de Mônaco', 'MC', 'MCO', '492', '.mc'),
       ('Qatar', 'QA', 'QAT', '634', '.qa'),
       ('Quênia', 'KE', 'KEN', '404', '.ke'),
       ('Quirguizistão', 'KG', 'KGZ', '417', '.kg'),
       ('Reino Unido', 'GB', 'GBR', '826', '.uk'),
       ('República Centro-Africana', 'CF', 'CAF', '140', '.cf'),
       ('República Democrática do Congo', 'CD', 'COD', '180', '.cd'),
       ('República do Congo', 'CG', 'COG', '178', '.cg'),
       ('República Dominicana', 'DO', 'DOM', '214', '.do'),
       ('Romênia', 'RO', 'ROU', '642', '.ro'),
       ('Ruanda', 'RW', 'RWA', '646', '.rw'),
       ('Rússia', 'RU', 'RUS', '643', '.ru'),
       ('Saara Ocidental', 'EH', 'ESH', '732', '.eh'),
       ('Samoa', 'WS', 'WSM', '882', '.ws'),
       ('Samoa Americana', 'AS', 'ASM', '016', '.as'),
       ('Santa Helena, Ascensão e Tristão da Cunha', 'SH', 'SHN', '654', '.sh'),
       ('Santa Lúcia', 'LC', 'LCA', '662', '.lc'),
       ('Santo Bartolomeu', 'BL', 'BLM', '652', '.bl'),
       ('São Marino', 'SM', 'SMR', '674', '.sm'),
       ('São Martinho', 'MF', 'MAF', '663', '.mf'),
       ('São Pedro e Miquelon', 'PM', 'SPM', '666', '.pm'),
       ('São Tomé e Príncipe', 'ST', 'STP', '678', '.st'),
       ('São Vicente e as Granadinas', 'VC', 'VCT', '670', '.vc'),
       ('Senegal', 'SN', 'SEN', '686', '.sn'),
       ('Serra Leoa', 'SL', 'SLE', '694', '.sl'),
       ('Sérvia', 'RS', 'SRB', '688', '.rs'),
       ('Seychelles', 'SC', 'SYC', '690', '.sc'),
       ('Sint Maarten', 'SX', 'SXM', '534', '.sx'),
       ('Síria', 'SY', 'SYR', '760', '.sy'),
       ('Somália', 'SO', 'SOM', '706', '.so'),
       ('Sri Lanka', 'LK', 'LKA', '144', '.lk'),
       ('St. Kitts e Nevis', 'KN', 'KNA', '659', '.kn'),
       ('Sudão', 'SD', 'SDN', '729', '.sd'),
       ('Sudão do Sul', 'SS', 'SSD', '728', '.ss'),
       ('Suécia', 'SE', 'SWE', '752', '.se'),
       ('Suíça', 'CH', 'CHE', '756', '.ch'),
       ('Suriname', 'SR', 'SUR', '740', '.sr'),
       ('Svalbard e Jan Mayen', 'SJ', 'SJM', '744', '.sj'),
       ('Tailândia', 'TH', 'THA', '764', '.th'),
       ('Taiwan', 'TW', 'TWN', '158', '.tw'),
       ('Tajiquistão', 'TJ', 'TJK', '762', '.tj'),
       ('Tanzânia', 'TZ', 'TZA', '834', '.tz'),
       ('Tcheca', 'CZ', 'CZE', '203', '.cz'),
       ('Território Britânico do Oceano Índico', 'IO', 'IOT', '086', '.io'),
       ('Territórios Franceses do Sul e Antártico', 'TF', 'ATF', '260', '.tf'),
       ('Timor Leste', 'TL', 'TLS', '626', '.tl'),
       ('Togo', 'TG', 'TGO', '768', '.tg'),
       ('Tokelau', 'TK', 'TKL', '772', '.tk'),
       ('Tonga', 'TO', 'TON', '776', '.to'),
       ('Trinidad e Tobago', 'TT', 'TTO', '780', '.tt'),
       ('Tunísia', 'TN', 'TUN', '788', '.tn'),
       ('Turcomenistão', 'TM', 'TKM', '795', '.tm'),
       ('Turquia', 'TR', 'TUR', '792', '.tr'),
       ('Tuvalu', 'TV', 'TUV', '798', '.tv'),
       ('Ucrânia', 'UA', 'UKR', '804', '.ua'),
       ('Uganda', 'UG', 'UGA', '800', '.ug'),
       ('Uruguai', 'UY', 'URY', '858', '.uy'),
       ('Uzbequistão', 'UZ', 'UZB', '860', '.uz'),
       ('Vanuatu', 'VU', 'VUT', '548', '.vu'),
       ('Venezuela', 'VE', 'VEN', '862', '.ve'),
       ('Vietnã', 'VN', 'VNM', '704', '.vn'),
       ('Wallis e Futuna', 'WF', 'WLF', '876', '.wf'),
       ('Zâmbia', 'ZM', 'ZMB', '894', '.zm'),
       ('Zimbábue', 'ZW', 'ZWE', '716', '.zw');